[package]
name = "actix_rustls_022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.5.1", features = ["rustls-0_22"] }
rustls = "0.22.2"
rustls-pemfile = "2.0.0"
